// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/movie-api/movie-api.proto

/*
Package movie_api is a generated protocol buffer package.

It is generated from these files:
	proto/movie-api/movie-api.proto

It has these top-level messages:
	Movie
	Response
	Error
*/
package movie_api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Movie struct {
	Imdb    string `protobuf:"bytes,1,opt,name=imdb" json:"imdb,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Year    uint32 `protobuf:"varint,3,opt,name=year" json:"year,omitempty"`
	Country string `protobuf:"bytes,4,opt,name=country" json:"country,omitempty"`
	Genre   string `protobuf:"bytes,5,opt,name=genre" json:"genre,omitempty"`
	Plot    string `protobuf:"bytes,6,opt,name=plot" json:"plot,omitempty"`
	Rating  string `protobuf:"bytes,7,opt,name=rating" json:"rating,omitempty"`
}

func (m *Movie) Reset()                    { *m = Movie{} }
func (m *Movie) String() string            { return proto.CompactTextString(m) }
func (*Movie) ProtoMessage()               {}
func (*Movie) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Movie) GetImdb() string {
	if m != nil {
		return m.Imdb
	}
	return ""
}

func (m *Movie) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Movie) GetYear() uint32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *Movie) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Movie) GetGenre() string {
	if m != nil {
		return m.Genre
	}
	return ""
}

func (m *Movie) GetPlot() string {
	if m != nil {
		return m.Plot
	}
	return ""
}

func (m *Movie) GetRating() string {
	if m != nil {
		return m.Rating
	}
	return ""
}

type Response struct {
	Movie  *Movie   `protobuf:"bytes,1,opt,name=movie" json:"movie,omitempty"`
	Movies []*Movie `protobuf:"bytes,2,rep,name=movies" json:"movies,omitempty"`
	Errors []*Error `protobuf:"bytes,3,rep,name=errors" json:"errors,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetMovie() *Movie {
	if m != nil {
		return m.Movie
	}
	return nil
}

func (m *Response) GetMovies() []*Movie {
	if m != nil {
		return m.Movies
	}
	return nil
}

func (m *Response) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type Error struct {
	Code        int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*Movie)(nil), "movie.api.Movie")
	proto.RegisterType((*Response)(nil), "movie.api.Response")
	proto.RegisterType((*Error)(nil), "movie.api.Error")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for MovieAPI service

type MovieAPIClient interface {
	Get(ctx context.Context, in *Movie, opts ...client.CallOption) (*Response, error)
}

type movieAPIClient struct {
	c           client.Client
	serviceName string
}

func NewMovieAPIClient(serviceName string, c client.Client) MovieAPIClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "movie.api"
	}
	return &movieAPIClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *movieAPIClient) Get(ctx context.Context, in *Movie, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "MovieAPI.Get", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MovieAPI service

type MovieAPIHandler interface {
	Get(context.Context, *Movie, *Response) error
}

func RegisterMovieAPIHandler(s server.Server, hdlr MovieAPIHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&MovieAPI{hdlr}, opts...))
}

type MovieAPI struct {
	MovieAPIHandler
}

func (h *MovieAPI) Get(ctx context.Context, in *Movie, out *Response) error {
	return h.MovieAPIHandler.Get(ctx, in, out)
}

func init() { proto.RegisterFile("proto/movie-api/movie-api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x4d, 0xd3, 0x4d, 0xdb, 0x29, 0x82, 0x8c, 0x22, 0x8b, 0x17, 0x43, 0x0e, 0x92, 0x8b,
	0x11, 0xea, 0x4d, 0xf0, 0xe0, 0x41, 0xc4, 0x83, 0x20, 0xfb, 0x06, 0x69, 0x32, 0x94, 0x05, 0xb3,
	0xbb, 0x6c, 0x56, 0xa1, 0x2f, 0xe0, 0x6b, 0xf8, 0xaa, 0xb2, 0x93, 0x54, 0x0b, 0xed, 0xed, 0x9f,
	0xef, 0xff, 0x99, 0xfc, 0x93, 0x85, 0x6b, 0xe7, 0x6d, 0xb0, 0x77, 0x9d, 0xfd, 0xd2, 0x74, 0x5b,
	0x3b, 0xfd, 0xaf, 0x2a, 0x76, 0x70, 0xc1, 0xa0, 0xaa, 0x9d, 0x2e, 0x7e, 0x12, 0x10, 0x6f, 0x71,
	0x42, 0x84, 0xa9, 0xee, 0xda, 0xb5, 0x4c, 0xf2, 0xa4, 0x5c, 0x28, 0xd6, 0x91, 0x99, 0xba, 0x23,
	0x39, 0x19, 0x58, 0xd4, 0x91, 0x6d, 0xa9, 0xf6, 0x32, 0xcd, 0x93, 0xf2, 0x54, 0xb1, 0x46, 0x09,
	0xb3, 0xc6, 0x7e, 0x9a, 0xe0, 0xb7, 0x72, 0xca, 0xd1, 0xdd, 0x88, 0x17, 0x20, 0x36, 0x64, 0x3c,
	0x49, 0xc1, 0x7c, 0x18, 0xe2, 0x0e, 0xf7, 0x61, 0x83, 0xcc, 0x86, 0xbd, 0x51, 0xe3, 0x25, 0x64,
	0xbe, 0x0e, 0xda, 0x6c, 0xe4, 0x8c, 0xe9, 0x38, 0x15, 0xdf, 0x09, 0xcc, 0x15, 0xf5, 0xce, 0x9a,
	0x9e, 0xf0, 0x06, 0x04, 0x77, 0xe7, 0x96, 0xcb, 0xd5, 0x59, 0xf5, 0x77, 0x49, 0xc5, 0x57, 0xa8,
	0xc1, 0xc6, 0x12, 0x32, 0x16, 0xbd, 0x9c, 0xe4, 0xe9, 0xd1, 0xe0, 0xe8, 0xc7, 0x24, 0x79, 0x6f,
	0x7d, 0x2f, 0xd3, 0x83, 0xe4, 0x73, 0x34, 0xd4, 0xe8, 0x17, 0x8f, 0x20, 0x18, 0xc4, 0xf6, 0x8d,
	0x6d, 0x87, 0x0e, 0x42, 0xb1, 0xc6, 0x1c, 0x96, 0x2d, 0xf5, 0x8d, 0xd7, 0x2e, 0x68, 0x6b, 0xc6,
	0x1f, 0xb6, 0x8f, 0x56, 0x0f, 0x30, 0xe7, 0x2f, 0x3f, 0xbd, 0xbf, 0x62, 0x05, 0xe9, 0x0b, 0x05,
	0x3c, 0x68, 0x75, 0x75, 0xbe, 0x47, 0x76, 0x47, 0x17, 0x27, 0xeb, 0x8c, 0xdf, 0xed, 0xfe, 0x37,
	0x00, 0x00, 0xff, 0xff, 0xa6, 0xfa, 0x85, 0x5d, 0xda, 0x01, 0x00, 0x00,
}
