// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/movieapi/movieapi.proto

/*
Package movieapi is a generated protocol buffer package.

It is generated from these files:
	proto/movieapi/movieapi.proto

It has these top-level messages:
	GetRequest
	ListRequest
	Movie
	Response
	Error
*/
package movieapi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ListRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Page uint32 `protobuf:"varint,2,opt,name=page" json:"page,omitempty"`
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ListRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type Movie struct {
	Imdb   string `protobuf:"bytes,1,opt,name=imdb" json:"imdb,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Year   string `protobuf:"bytes,3,opt,name=year" json:"year,omitempty"`
	Poster string `protobuf:"bytes,4,opt,name=poster" json:"poster,omitempty"`
	Genre  string `protobuf:"bytes,5,opt,name=genre" json:"genre,omitempty"`
	Plot   string `protobuf:"bytes,6,opt,name=plot" json:"plot,omitempty"`
	Rating string `protobuf:"bytes,7,opt,name=rating" json:"rating,omitempty"`
}

func (m *Movie) Reset()                    { *m = Movie{} }
func (m *Movie) String() string            { return proto.CompactTextString(m) }
func (*Movie) ProtoMessage()               {}
func (*Movie) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Movie) GetImdb() string {
	if m != nil {
		return m.Imdb
	}
	return ""
}

func (m *Movie) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Movie) GetYear() string {
	if m != nil {
		return m.Year
	}
	return ""
}

func (m *Movie) GetPoster() string {
	if m != nil {
		return m.Poster
	}
	return ""
}

func (m *Movie) GetGenre() string {
	if m != nil {
		return m.Genre
	}
	return ""
}

func (m *Movie) GetPlot() string {
	if m != nil {
		return m.Plot
	}
	return ""
}

func (m *Movie) GetRating() string {
	if m != nil {
		return m.Rating
	}
	return ""
}

type Response struct {
	Movie  *Movie   `protobuf:"bytes,1,opt,name=movie" json:"movie,omitempty"`
	Movies []*Movie `protobuf:"bytes,2,rep,name=movies" json:"movies,omitempty"`
	Errors []*Error `protobuf:"bytes,3,rep,name=errors" json:"errors,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Response) GetMovie() *Movie {
	if m != nil {
		return m.Movie
	}
	return nil
}

func (m *Response) GetMovies() []*Movie {
	if m != nil {
		return m.Movies
	}
	return nil
}

func (m *Response) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type Error struct {
	Code        int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*GetRequest)(nil), "movieapi.GetRequest")
	proto.RegisterType((*ListRequest)(nil), "movieapi.ListRequest")
	proto.RegisterType((*Movie)(nil), "movieapi.Movie")
	proto.RegisterType((*Response)(nil), "movieapi.Response")
	proto.RegisterType((*Error)(nil), "movieapi.Error")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for MovieAPI service

type MovieAPIClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*Response, error)
	List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*Response, error)
}

type movieAPIClient struct {
	c           client.Client
	serviceName string
}

func NewMovieAPIClient(serviceName string, c client.Client) MovieAPIClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "movieapi"
	}
	return &movieAPIClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *movieAPIClient) Get(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "MovieAPI.Get", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieAPIClient) List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "MovieAPI.List", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MovieAPI service

type MovieAPIHandler interface {
	Get(context.Context, *GetRequest, *Response) error
	List(context.Context, *ListRequest, *Response) error
}

func RegisterMovieAPIHandler(s server.Server, hdlr MovieAPIHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&MovieAPI{hdlr}, opts...))
}

type MovieAPI struct {
	MovieAPIHandler
}

func (h *MovieAPI) Get(ctx context.Context, in *GetRequest, out *Response) error {
	return h.MovieAPIHandler.Get(ctx, in, out)
}

func (h *MovieAPI) List(ctx context.Context, in *ListRequest, out *Response) error {
	return h.MovieAPIHandler.List(ctx, in, out)
}

func init() { proto.RegisterFile("proto/movieapi/movieapi.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x4d, 0x4b, 0x03, 0x31,
	0x10, 0x75, 0xbb, 0xdd, 0xb5, 0x4e, 0x11, 0x61, 0xa8, 0x12, 0x04, 0x61, 0x59, 0x10, 0x7b, 0xaa,
	0xd8, 0xe2, 0xd1, 0x83, 0x07, 0x29, 0x82, 0x82, 0xe4, 0x1f, 0x6c, 0xdb, 0xa1, 0x04, 0xec, 0x26,
	0x26, 0x51, 0xf0, 0xec, 0xef, 0xf0, 0xbf, 0x4a, 0x26, 0xdb, 0xdd, 0x2a, 0xc5, 0xdb, 0x9b, 0xf7,
	0x26, 0x6f, 0xbe, 0x02, 0x17, 0xc6, 0x6a, 0xaf, 0xaf, 0x37, 0xfa, 0x43, 0x51, 0x65, 0x54, 0x0b,
	0x26, 0xcc, 0xe3, 0x60, 0x1b, 0x97, 0x05, 0xc0, 0x9c, 0xbc, 0xa4, 0xb7, 0x77, 0x72, 0x1e, 0x11,
	0xfa, 0x75, 0xb5, 0x21, 0x91, 0x14, 0xc9, 0xf8, 0x48, 0x32, 0x2e, 0x6f, 0x61, 0xf8, 0xa4, 0xdc,
	0x7f, 0x29, 0x81, 0x33, 0xd5, 0x9a, 0x44, 0xaf, 0x48, 0xc6, 0xc7, 0x92, 0x71, 0xf9, 0x9d, 0x40,
	0xf6, 0x1c, 0xaa, 0x04, 0x55, 0x6d, 0x56, 0x8b, 0xed, 0x8b, 0x80, 0x5b, 0x97, 0xde, 0x6f, 0x97,
	0x4f, 0xaa, 0xac, 0x48, 0x23, 0x17, 0x30, 0x9e, 0x41, 0x6e, 0xb4, 0xf3, 0x64, 0x45, 0x9f, 0xd9,
	0x26, 0xc2, 0x11, 0x64, 0x6b, 0xaa, 0x2d, 0x89, 0x8c, 0xe9, 0x18, 0x70, 0x1f, 0xaf, 0xda, 0x8b,
	0x3c, 0x3a, 0x04, 0x1c, 0x1c, 0x6c, 0xe5, 0x55, 0xbd, 0x16, 0x87, 0xd1, 0x21, 0x46, 0xe5, 0x57,
	0x02, 0x03, 0x49, 0xce, 0xe8, 0xda, 0x11, 0x5e, 0x42, 0xc6, 0x1b, 0xe1, 0x1e, 0x87, 0xd3, 0x93,
	0x49, 0xbb, 0x2f, 0x1e, 0x41, 0x46, 0x15, 0xaf, 0x20, 0x67, 0xe0, 0x44, 0xaf, 0x48, 0xf7, 0xe5,
	0x35, 0x72, 0x48, 0x24, 0x6b, 0xb5, 0x75, 0x22, 0xfd, 0x9b, 0xf8, 0x10, 0x78, 0xd9, 0xc8, 0xe5,
	0x1d, 0x64, 0x4c, 0x84, 0xd6, 0x97, 0x7a, 0x15, 0x1b, 0xc8, 0x24, 0x63, 0x2c, 0x60, 0xb8, 0x22,
	0xb7, 0xb4, 0xca, 0x78, 0xa5, 0xeb, 0x66, 0x57, 0xbb, 0xd4, 0xd4, 0xc2, 0x80, 0x0b, 0xdf, 0xbf,
	0x3c, 0xe2, 0x0d, 0xa4, 0x73, 0xf2, 0x38, 0xea, 0x4a, 0x75, 0x87, 0x3d, 0xc7, 0x8e, 0xdd, 0x0e,
	0x5d, 0x1e, 0xe0, 0x0c, 0xfa, 0xe1, 0xb4, 0x78, 0xda, 0xa9, 0x3b, 0xa7, 0xde, 0xff, 0x68, 0x91,
	0xf3, 0x17, 0x9a, 0xfd, 0x04, 0x00, 0x00, 0xff, 0xff, 0x59, 0x99, 0x33, 0x4f, 0x63, 0x02, 0x00,
	0x00,
}
